"""empty message

Revision ID: 0da664bbb338
Revises: 
Create Date: 2021-05-03 12:33:02.636535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da664bbb338'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'project', 'subject', ['subject_id'], ['id'])
    op.drop_column('project', 'user')
    op.drop_column('project', 'subject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('subject', sa.INTEGER(), nullable=False))
    op.add_column('project', sa.Column('user', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'subject', ['subject'], ['id'])
    op.create_foreign_key(None, 'project', 'user', ['user'], ['id'])
    op.drop_column('project', 'user_id')
    op.drop_column('project', 'subject_id')
    # ### end Alembic commands ###
