"""empty message

Revision ID: 19eb58ca79dc
Revises: b07def24d61f
Create Date: 2021-05-04 21:01:35.969297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19eb58ca79dc'
down_revision = 'b07def24d61f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_url', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_project_slug'), ['slug'])

        batch_op.drop_column('user_id')

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_subject_slug'), ['slug'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])

    with op.batch_alter_table('user_type', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_type_slug'), ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_type', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_type_slug'), type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_subject_slug'), type_='unique')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_project_slug'), type_='unique')
        batch_op.drop_column('site_url')

    # ### end Alembic commands ###
