"""empty message

Revision ID: 40194945a654
Revises: 5fd3cb26f007
Create Date: 2021-05-10 14:30:54.804091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40194945a654'
down_revision = '5fd3cb26f007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_confirmed')

    # ### end Alembic commands ###
