"""empty message

Revision ID: 759baca2b0e8
Revises: 
Create Date: 2021-04-26 21:16:58.734726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759baca2b0e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_project')
    op.add_column('project', sa.Column('path_to_index', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'path_to_index')
    op.create_table('site_project',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('path_to_index', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='site_project_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='site_project_pkey')
    )
    # ### end Alembic commands ###
