"""empty message

Revision ID: 8f23ee41f451
Revises: 19eb58ca79dc
Create Date: 2021-05-07 16:03:38.937253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f23ee41f451'
down_revision = '19eb58ca79dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_suggest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sent', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_project_suggest_project_id_project')),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('fk_project_suggest_sender_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_suggest'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_suggest')
    # ### end Alembic commands ###
