"""empty message

Revision ID: afc82caf0df4
Revises: 4bbfeeb03cff
Create Date: 2021-05-04 19:39:37.915071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc82caf0df4'
down_revision = '4bbfeeb03cff'
branch_labels = None
depends_on = None

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_project_slug'), ['slug'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_subject_slug'), ['slug'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])

    with op.batch_alter_table('user_type', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_type_slug'), ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_type', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_type_slug'), type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_subject_slug'), type_='unique')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_project_slug'), type_='unique')

    # ### end Alembic commands ###
