"""empty message

Revision ID: b07def24d61f
Revises: afc82caf0df4
Create Date: 2021-05-04 19:45:20.317725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07def24d61f'
down_revision = 'afc82caf0df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_project_slug'), ['slug'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_subject_slug'), ['slug'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])

    with op.batch_alter_table('user_type', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_type_slug'), ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_type', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_type_slug'), type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_subject_slug'), type_='unique')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_project_slug'), type_='unique')

    # ### end Alembic commands ###
