"""empty message

Revision ID: db6820e27127
Revises: 0da664bbb338
Create Date: 2021-05-04 18:26:47.644375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6820e27127'
down_revision = '0da664bbb338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('has_photo', sa.Boolean(), nullable=True))
    op.alter_column('project', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('project', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('project', 'has_photo')
    # ### end Alembic commands ###
